name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: zip, mbstring, ctype

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.3-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check syntax errors
      run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

    - name: Run security check
      run: |
        if command -v security-checker &> /dev/null; then
          security-checker security:check composer.lock
        else
          echo "Security checker not available, skipping..."
        fi

    - name: Validate code structure
      run: |
        echo "Checking for required files..."
        [ -f "composer.json" ] || { echo "composer.json missing"; exit 1; }
        [ -f "phpunit.xml" ] || { echo "phpunit.xml missing"; exit 1; }
        [ -d "tests" ] || { echo "tests directory missing"; exit 1; }
        [ -d "src" ] || { echo "src directory missing"; exit 1; }
        echo "All required files present ✓"